<a href="https://colab.research.google.com/github/Sathvara-Amitkumar/RNN_Next-Word-Prediction/blob/main/next_word_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
cd /content/drive/MyDrive/Colab Notebooks/RNN/

/content/drive/MyDrive/Colab Notebooks/RNN

In [12]:
ls

next_word_predictor.ipynb  qoute_dataset.csv

In [13]:
df = pd.read_csv('qoute_dataset.csv')

In [14]:
df.shape

(3038, 2)

In [15]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [16]:
df['quote'][0]

'“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

In [18]:
quotes = df['quote']
quotes

0       “The world as we have created it is a process ...
1       “It is our choices, Harry, that show what we t...
2       “There are only two ways to live your life. On...
3       “The person, be it gentleman or lady, who has ...
4       “Imperfection is beauty, madness is genius and...
                              ...
3033        The past beats inside me like a second heart.
3034    Damn, Claire. Warn a guy before you do a face-...
3035    Can you be a girl for a few seconds?""I'm alwa...
3036    That's what fiction is for. It's for getting a...
3037    If we have no peace, it is because we have for...
Name: quote, Length: 3038, dtype: object

In [20]:
quotes = quotes.str.lower()

In [22]:
import string
translater = str.maketrans(' ', ' ', string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translater))

In [25]:
quotes.sample(5)

2728    this is a new year a new beginning and things ...
2968                    dont let the muggles get you down
422     love is needing someone love is putting up wit...
1960    if you end up with a boring miserable life bec...
179                    everything you can imagine is real
Name: quote, dtype: object